package GUI;

import CodeGen.Code;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;

public class InputOutputFrame extends javax.swing.JFrame {

    /** Creates new form InputOutputFrame */
    public InputOutputFrame() {
        //inicializacija na vizuelnite komponenti dodadeni od NetBeans
        initComponents();

        //look & feel layout na glavnata forma
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
           }
        catch(Exception exc)
        {
        }

        //setiranje na izmenlivosta na text poleto kade shto ke se chuva kodot
        jTextField2.setEditable(false);

        //inicijalizacija  na CheckBoxes
        jCheckBox1.setSelected(true);
        jCheckBox2.setSelected(true);       
        jCheckBox3.setSelected(true);
        jCheckBox4.setSelected(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Код генератор");
        setBackground(java.awt.SystemColor.window);
        setBounds(new java.awt.Rectangle(0, 0, 252, 263));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Подесувања", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Serif", 0, 12));

        jTextField1.setName(""); // NOI18N

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton1.setFont(new java.awt.Font("Serif", 0, 12));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Serif", 0, 12));
        jCheckBox1.setText("мали букви");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Handler(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Serif", 0, 12));
        jCheckBox2.setText("големи букви");

        jCheckBox3.setFont(new java.awt.Font("Serif", 0, 12));
        jCheckBox3.setText("специални знаци");

        jCheckBox4.setFont(new java.awt.Font("Serif", 0, 12));
        jCheckBox4.setText("броеви");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 12));
        jLabel1.setText("Знаци кои сакате да се содржат во кодот:");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 12));
        jLabel2.setText("Број на знаци:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox3))
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox4)
                                .addComponent(jCheckBox2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Код:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Serif", 0, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Serif", 0, 12));
        jButton2.setText("Излез");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton2)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n;
        
        try{
            n = Integer.parseInt(jTextField1.getText());
         
            Code C = new Code(n);
            C.CodeGenerator();

            if ( (jCheckBox1.isSelected()) && (jCheckBox2.isSelected())
               && (jCheckBox3.isSelected()) && (jCheckBox4.isSelected()) )
                C.CodeGenerator();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==false) )
                C.SmallLetters();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==false) )
                C.CapitalLetters();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==false) )
                C.SpecialCharacters();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==true) )
                C.OnlyDigits();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==false) )
                C.OnlyLetters();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==false) )
                C.SmallLetters_SpecialCharacters();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==true) )
                C.SmallLetters_Digits();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==false) )
                C.CapitalLetters_SpecialCharacters();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==true) )
                C.CapitalLetters_Digits();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==false)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==true) )
                C.NoLetters();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==false) )
                C.NoNumbers();

            else if ( (jCheckBox1.isSelected()==true) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==false) &&
               (jCheckBox4.isSelected()==true) )
                C.NoCharacters();

            else if ( (jCheckBox1.isSelected()==false) &&
                    (jCheckBox2.isSelected()==true)
               && (jCheckBox3.isSelected()==true) &&
               (jCheckBox4.isSelected()==true) )
                C.NoSmallLetters();

            jTextField2.setText(C.stringCode());
            
            if (n == 0)
            {
                IncorrectDataDialog.showZero();
                jTextField1.setText("");
            }
         } catch (NumberFormatException exc)
         {
             if (jTextField1.getText().isEmpty())
             {
                 IncorrectDataDialog.showEmpty();
                 jTextField1.setText("");
                 jTextField2.setText("");
             }
             else 
             {
                 IncorrectDataDialog.show();
                 jTextField1.setText("");
                 jTextField2.setText("");
             }
         }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Handler(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Handler
        // TODO add your handling code here:
    }//GEN-LAST:event_Handler

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
